const darkTheme = {
  ".rdev-dark": {
    "--rdev-colors-brand": "hsla(var(--palette-blue-35), 100%)",
    "--rdev-colors-body": "hsla(var(--palette-gray-90), 100%)",
    "--rdev-colors-header": "hsla(var(--palette-gray-90), 40%)",
    "--rdev-colors-emphasis": "hsla(var(--palette-blue-35), 10%)",
    "--rdev-colors-foreground": "hsla(var(--palette-gray-80), 60%)",
    "--rdev-colors-danger": "hsla(var(--palette-red-30), 100%)",
    "--rdev-colors-danger-emphasis": "hsla(var(--palette-red-40), 15%)",
    "--rdev-colors-warning": "hsla(var(--palette-orange-45), 100%)",
    "--rdev-colors-warning-emphasis": "hsla(var(--palette-orange-45), 15%)",
    "--rdev-colors-success": "hsla(var(--palette-green-45), 100%)",
    "--rdev-colors-success-emphasis": "hsla(var(--palette-green-45), 15%)",
    "--rdev-colors-typeface-primary": "hsla(var(--palette-indigo-05), 100%)",
    "--rdev-colors-typeface-secondary": "hsla(var(--palette-gray-35), 100%)",
    "--rdev-colors-typeface-tertiary": "hsla(var(--palette-gray-20), 100%)",
    "--rdev-colors-typeface-danger": "hsla(var(--palette-red-20), 100%)",
    "--rdev-border-color": "hsl(var(--palette-gray-80))",
    "--rdev-card-background-color": "hsl(var(--palette-gray-88))",
    "--rdev-form-input-active": "var(--rdev-colors-brand)",
    "--rdev-form-input-background": "hsl(var(--palette-gray-100))",
    "--rdev-form-input-disabled": "hsl(var(--palette-gray-55))",
    "--rdev-form-input-border": "hsl(var(--palette-gray-60))",
    "--rdev-form-input-focus": "hsla(var(--palette-blue-50), 1)",
    "--shadow-color": "var(--local-shadow-color, 223deg 5% 1%)",
    "--code-snippet-background": "hsla(var(--palette-gray-85), 0.5)",
    "--token-comment": "var(--rdev-colors-typeface-tertiary)",
    "--token-selector": "hsl(var(--palette-indigo-20))",
    "--token-symbol": "hsl(var(--palette-blue-35))",
    "--token-operator": "hsl(var(--palette-orange-35))",
    "--token-keyword": "hsl(var(--palette-blue-30))",
    "--token-function": "hsl(var(--palette-pink-35))",
    "--token-punctuation": "hsl(var(--palette-indigo-20))",
  },
}

export default darkTheme
