const lightTheme = {
  ".rdev-light": {
    "--rdev-colors-brand": "hsla(var(--palette-blue-50), 100%)",
    "--rdev-colors-body": "hsla(var(--palette-gray-02), 100%)",
    "--rdev-colors-header": "hsla(var(--palette-gray-02), 40%)",
    "--rdev-colors-emphasis": "hsla(var(--palette-blue-50), 5%)",
    "--rdev-colors-foreground": "hsla(var(--palette-gray-05), 60%)",
    "--rdev-colors-danger": "hsla(var(--palette-red-55), 100%)",
    "--rdev-colors-danger-emphasis": "hsla(var(--palette-red-15), 15%)",
    "--rdev-colors-warning": "hsla(var(--palette-orange-80), 100%)",
    "--rdev-colors-warning-emphasis": "hsla(var(--palette-orange-45), 15%)",
    "--rdev-colors-success": "hsl(var(--palette-green-80))",
    "--rdev-colors-success-emphasis": "hsla(var(--palette-green-45), 15%)",
    "--rdev-colors-typeface-primary": "hsla(var(--palette-indigo-90), 100%)",
    "--rdev-colors-typeface-secondary": "hsla(var(--palette-gray-55), 100%)",
    "--rdev-colors-typeface-tertiary": "hsla(var(--palette-gray-60), 100%)",
    "--rdev-colors-typeface-danger": "hsla(var(--palette-red-60), 100%)",
    "--rdev-border-color": "var(--rdev-colors-emphasis)",
    "--rdev-card-background-color": "hsl(var(--palette-gray-01))",
    "--rdev-form-input-active": "var(--rdev-colors-brand)",
    "--rdev-form-input-background": "hsl(var(--palette-gray-00))",
    "--rdev-form-input-disabled": "hsl(var(--palette-gray-09))",
    "--rdev-form-input-border": "hsl(var(--palette-blue-10))",
    "--rdev-form-input-focus": "hsla(var(--palette-blue-40), 0.55)",
    "--shadow-color": "var(--local-shadow-color, 223deg 5% 80%)",
    "--code-snippet-background": "hsla(var(--palette-gray-03), 0.2)",
    "--token-comment": "var(--rdev-colors-typeface-tertiary)",
    "--token-selector": "hsl(var(--palette-indigo-50))",
    "--token-symbol": "hsl(var(--palette-blue-60))",
    "--token-operator": "hsl(var(--palette-orange-75))",
    "--token-keyword": "hsl(var(--palette-blue-50))",
    "--token-function": "hsl(var(--palette-pink-60))",
    "--token-punctuation": "hsl(var(--palette-indigo-60))",
  },
}

export default lightTheme
